export const mensajeria = {
     
    mensajero1:[
        {
            nombre:"Wilson",
            edad:"38",
            cargo:"lider",
            dirección:"belen",
            ciudad:"medellin"
        }
    ],
    mensajero2:[
        {
            nombre:"Rueda",
            edad:"32",
            cargo:"domiciliario",
            dirección:"violetas",
            ciudad:"medellin"
        }
    ],
    mensajero3:[
        {
            nombre:"Jose miguel",
            edad:"45",
            cargo:"domiciliario",
            dirección:"bello",
            ciudad:"medellin"
        }
    ],
    mensajero4:[
        {
            nombre:"Victor",
            edad:"27",
            cargo:"domiciliario",
            dirección:"itagui",
            ciudad:"medellin"
        }
    ],
    mensajero5:[
        {
            nombre:"Carlos Andres",
            edad:"22",
            cargo:"Despachador",
            dirección:"america",
            ciudad:"bogota"
        }
    ],
    mensajero6:[
        {
            nombre:"Velez",
            edad:"41",
            cargo:"Auxiliar",
            dirección:"poblado",
            ciudad:"cali-valle"
        }
    ],
    mensajero7:[
        {
            nombre:"Rolando",
            edad:"38",
            cargo:"jefe",
            dirección:"Salgar",
            ciudad:"españa"
        }
    ],
    mensajero8:[
        {
            nombre:"Fernando",
            edad:"35",
            cargo:"Auxiliar",
            dirección:"Morroplancho",
            ciudad:"Cartagena"
        }
    ],
    mensajero9:[
        {
            nombre:"Juan paulo",
            edad:"24",
            cargo:"domiciliario",
            dirección:"planchon",
            ciudad:"Cartagena"
        }
    ],
    mensajero10:[
        {
            nombre:"Paolo",
            edad:"19",
            cargo:"domiciliario",
            dirección:"arenal",
            ciudad:"Cartagena"
        }
    ]
}
